#!/system/bin/env bash

. ~/etc/bash/functions.d/msg.sh
. ~/etc/bash/functions.d/debug.sh

_strict on

OUT='./adbfu.log'
ADB_SHELL=''
MODE=''
USER="${USER:-`whoami`}"
PKGS=''
DEBUG=${DEBUG:-0}

_cleanup() {
	unset ADB_SHELL
	unset _pm rmpkg
  exit
}


##
## parseArgs <ARGUMENTS LIST>
##
## Takes a list of arguments that includes both packages and
## permissions, and returns two arrays containing the two split
## nicely into their own arrays
##
parseArgs() {
	[[ -n "${1:-}" ]] || bug 'parseArgs() called with no arguments!'

	declare -g -a pkgList permList
	local divFound=0

	while [ -n "${1:-}" ]; do
		case $1 in
			'--')
				divFound=1
				;;
			*)
				if ! (( divFound )); then
					pkgList+=( $1 )
				else
					permList+=( $1 )
				fi
				;;
		esac
		shift 1
	done
}

usage() {
	msg "Usage: $(basename $0) <OPERATION> [PKG LIST]" 1>&2
	msg "  OPERATION is one of ..."
	msg "      -c|--clear"
	msg "      -l|--list"
	msg "      -r|--remove"
 	msg "      -p|--print-label"
	exit ${1:-255}
}

usage_grant() {
	msg "adbfu grant <APP> <PERMISSION(S)>"
	msg "  APP can be either a single package name, or a group of"
	msg "  packages, i.e., system, thirdparty, or all*."
	msg "  PERMISSION is one or more Android system permissions, fully"
	msg "  spelled out (no shortcuts)"
	exit ${1:-255}
}

adb_pm() {
  (( DEBUG )) && msg "$bold${red}EXEC${wht}  pm $@\n"
	adb shell pm "$@" 2>>$OUT
}

list_permissions() {
	case "${1:-fuckit}" in
		sys*)
			adb_pm list permissions | sed 's,^permission:,,' | sort
			;;
		*)
			;;
	esac
}

list_packages() {
	local pm_arg=''

	case "${1:-all}" in
		sys*)
			pm_arg='-s' ;;
		user)
			pm_arg='-3' ;;
		*)
			;;
	esac

	adb_pm list packages $pm_arg | sed 's,^package:,,' | sort
}

list_system_pkgs() {
  adb_pm list packages -s | sed 's,^package:,,' | sort
}

##
## grant_perms <PACKAGE> <PERMISSION> [PERMISSION2] ...
##
grant_perms() {
	[ $# -ge 2 ] || return 1
	local pkg="$1" ; shift
	local perms=($@)
	local tmpperm

	case "$pkg" in
		com.termux*) return ;;
	esac

	for tmpperm in "${perms[@]}" ; do
		set +e
		adb_pm grant $pkg $tmpperm &&
			msg "$bold$blu$pkg $rst-> $bold$cyn$tmpperm ${grn}granted$rst"
		set -e
	done
}

get_user_ids() {
	adb_pm list users | \
		grep 'UserInfo' | \
		sed 's,^.*Info{\([0-9]*\):.*:.*}.*$,\1,'
}

get_user_name() {
	local users="$(get_user_ids)"
	local user

	for user in $users; do
		read num name <<< $(adb_pm list users | \
				grep 'UserInfo' | \
				sed 's,^.*Info{\([0-9]*\):\([A-Za-z].*[A-Za-z]\):c[0-9]*}.*$,\1 \2,')

		if [ $num -eq $1 ]; then
		# Found it
		 	echo "$name"
		 	break
		fi
	done
}

get_pkg_label() {
  [[ $# -eq 1 ]] || return 1

  local pkgname="$1"
  local pkgpath="$(adb_pm path $pkgname | \
                   sed 's,^package:,,')"

  _nofail -s adb pull "$pkgpath" "$pkgname.apk"

  aapt d badging $pkgname.apk | \
    grep '^application-label:' | \
    sed 's,^application-label:.\(.*\).$,\1,'

  rm -f "$pkgname.apk"
}

get_pkg_labels() {
  local pkgname label

  trap '_cleanup' INT HUP QUIT KILL EXIT

  for pkgname in "$@"; do
    label="$(get_pkg_label $pkgname)" || continue
#    if [ $(tput colors) -ge 8 ]; then
#      _msg "$bold$mag$pkgname$rst='$label'\n"
#    else
      msg "$pkgname\t$label"
#    fi
  done  
}

clear_caches() {
  _info "wiping system-wide cache"
  _pm trim-caches $((1024*1024*1024*512)) &>/dev/null || true
  _success

  echo

  msg "$bold${cyn}removing app cache/dex files..."
  for pkg in $(list_packages); do
    case $pkg in
      android*)
        continue ;;
			com.termux*)
				continue ;;
    esac

    _info "$pkg"
    adb_pm clear --user 0 --cache-only $pkg &>/dev/null || true
		adb_pm clear --user 10 --cache-only $pkg &>/dev/null || true
    adb_pm delete-dexopt $pkg &>/dev/null || true
#    adb_pm compile -f -m space-profile $pkg &>/dev/null || true
    adb_pm reconcile-secondary-dex-files $pkg &>/dev/null || true
    _success
  done
}

remove_package() {
	[[ $# -eq 1 ]] || return 1

#	local system_apps user_apps users user
#	system_apps="$(list_packages system)"
#	user_apps="$(list_packages user)"
	local pkg="$1"

#	for pkg in "$@"; do
#		if [ -n "$(echo $system_apps | grep $pkg)" ]; then
			# We have a system app
			_msg "${bold}removing $blu$pkg\n"

			_info "uninstalling updates"
			adb_pm uninstall-system-updates "$pkg" &>/dev/null || true
      _success

      _info "resetting permissions"
			adb_pm reset-permissions "$pkg" &>/dev/null || true
			adb_pm clear "$pkg" &>/dev/null || true
			_success

			for user in $(get_user_ids); do
				_info "disabling for user $user"
				adb_pm uninstall -k --user "$user" "$pkg" &>/dev/null || true
				adb_pm disable-user --user "$user" "$pkg" &>/dev/null || true
				_success
			done

#		elif [ -n "$(echo $user_apps | grep $pkg)" ]; then
#			# user app found
#			msg -n "${bold}uninstalling user package ${cyn}$pkg"
#			pm uninstall "$pkg"
#			msg " - ${grn}done"
#		else
#			msg "$cyn$pkg not found"
#		fi

		echo
#	done
}

remove_packages() {
	local pkg
	for pkg in "$@"; do
		remove_package "$pkg"
	done
}


################################
################################
## START OF THE ACTUAL SCRIPT ##
################################
################################
if [ "${USER}" = 'shell' -o "$USER" = 'root' ]; then
	ADB_SHELL=1
else
	ADB_SHELL=0
fi

declare -g -a pkgList permList

while [ -n "${1:-}" ]; do
	case $1 in
    c|clear)
      MODE='clear'
      shift 1
      ;;
		g|grant)
			case "${2:-help}" in
				''|help|-h|--help) usage_grant ;;
				system) pkgList=( $(list_packages system) ) ;;
				user)   pkgList=( $(list_packages user) ) ;;
			esac
			shift 1
			parseArgs "${@:-}"
			for pkg in "${pkgList[@]}" ; do
				grant_perms $pkg "${permList[@]}"
			done
			exit 0
			;;
    l|list)
      sub="${2:-}"
			list_packages "$sub"
			exit 0
      ;;
		r|remove)
			MODE='remove'
			shift 1
			;;
    p|print-label)
      MODE='label'
      shift 1
      ;;
		h|help)
			case "${2:-}" in
				clear)  usage_clear ;;
				grant)  usage_grant ;;
				list)   usage_list ;;
				remove) usage_remove ;;
				print*) usage_print_label ;;
				*)      usage 0 ;;
			esac
			;;
		-*)
			exit 255
			;;
		*)
			PKGS="$PKGS $1"
			shift 1
			;;
	esac
done

case "$MODE" in
  clear)
    clear_caches
    ;;
  label)
    get_pkg_labels $PKGS
    ;;
	remove)
		remove_packages $PKGS
		;;
	*)
		exit 237
		;;
esac

# vim: ts=2 sw=2 ft=bash ai
