#!/system/bin/env bash

FUNC_DIR=~/etc/bash/functions.d; export FUNC_DIR
. "$FUNC_DIR/msg.sh" || exit 1
. "$FUNC_DIR/confirm.sh" || exit 1
. "$FUNC_DIR/debug.sh" || exit 1

_strict on

confirm "Install static libraries alongside shared?" \
	&& STATIC_LIBS=1 || STATIC_LIBS=0

LUA_VERS=5.4

REPOS=(root-repo
       x11-repo
       tur-repo
       )

BASE_PKGS=(vim
           less
           man
           git
           texinfo
           update-info-dir
           patchelf
           ncftp
           ncurses-utils
           perl
           build-essential
           ninja
           cmake
           cmake-curses-gui
           proot
           proot-distro
           fakeroot
           bash-completion
           zsh
           zsh-completions
           openssh
           termux-api
           termux-services
           vivid
           fortune
           ccache
           libgmp
		   libmpfr
		   libmpc
	       libisl
		   libpopt
		   android-tools
           aapt
		   aapt2
		   tcl
		   expect
		   check
		   quilt
		   rsync
		   wget
		   wget2
           )


COMPRESSION_LIBS=(
	zlib
	pigz
	zstd
	pzstd
	liblzma
	xz-utils
	liblz4
	lz4
	liblzo
	lzop
	lzlib
	lzip
	plzip
	zopfli
    )
[[ "$TERMUX_MAIN_PACKAGE_FORMAT" = 'apt' ]] \
	&& COMPRESSION_LIBS+=(pixz)

if (( STATIC_LIBS )); then
	COMPRESSION_LIBS+=(zlib-static
					   zstd-static
					   liblzma-static
					   liblzo-static
					   lzlib-static
				       )
fi

if (( STATIC_LIBS )); then
	BASE_PKGS+=(libgmp-static
				libmpfr-static
				libmpc-static
				libisl-static
				libunistring-static
				libiconv-static
				libpopt-static
			    )
fi

PKGS=(apt-file
      elinks
      gettext
      libtool
      autoconf
      automake
      clang
      binutils
      binutils-gold
      llvmgold
      mold
	  autoconf
    automake
    bc
    bison
    cmake
	cmake-curses-gui
    flex
    gperf
    libtool
    m4
    golang
    proot
    python
    ruby
    rust
    subversion
      shellcheck
      hstr
      make-guile
      guile
      gh
	  glab-cli
      anacron
      graphviz
      doxygen
      libxml2-utils
      xmlto
      )

if (( STATIC_LIBS )); then
	PKGS+=(guile-static
	       libxml2-static
		   libxslt-static
	       )
fi


PYTHON_PKGS=(python
             python-pip
			 python-cryptography
		 )

PY3_MODULES=(wheel
	         setuptools
			 pylint
			 jinja2
             psutil
             meson
			 sphinx
		     )

RB_GEMS=(fpm)

NPM_MODULES=(acodeX-server)

LUA_PKGS=(lua51
	        liblua51
					luarocks
					lua${LUA_VERS/.}
					liblua${LUA_VERS/.}
					luarocks
			  	)
if (( STATIC_LIBS )); then	
	LUA_PKGS+=(liblua51-static
					   liblua${LUA_VERS/.}-static
  					 )
fi

confirm "Install RedHat Package Manager?" \
	&& RPM=1 || RPM=0

if (( RPM )); then
	BASE_PKGS+=(cpio rpm)
	PY3_MODULES+=(rpmlint)
fi

if [ -x "$(type -p nala)" ]; then
	declare -g NALA_INSTALLED=1
else
	declare -g NALA_INSTALLED=0
fi

# Termux Package Manager
pm_update() {
  [[ -n "${TERMUX_MAIN_PACKAGE_FORMAT:-}" ]] || return 1

  if [ "$TERMUX_MAIN_PACKAGE_FORMAT" = 'apt' ]; then
    _nofail apt-get update
    _nofail apt-get full-upgrade -y
  else
    _nofail pacman -Syu --noconfirm
  fi
}

pm_install() {
	[[ -n "${TERMUX_MAIN_PACKAGE_FORMAT:-}" ]] || return 1

	local pkg

	for pkg in "$@" ; do
		if [ "$TERMUX_MAIN_PACKAGE_FORMAT" = 'apt' ]; then
			if (( NALA_INSTALLED )); then
				_nofail nala install -y "$pkg"
			else
				_nofail apt-get install -y "$pkg"
			fi
		else
			_nofail pacman -S --noconfirm \
				--overwrite '*/data/*' "$pkg"
		fi
	done
}

pm_update
[[ "$TERMUX_MAIN_PACKAGE_FORMAT" = 'apt' ]] \
	&& pm_install "${REPOS[@]}"

#dfffif (( NALA )); then
#	pm_install python python-apt python-pip nala
#	declare -g NALA_INSTALLED=1
#fi

pm_install libtree-ldd ldd

pm_install mount-utils mksh # for the manpages, mostly
for bin in toybox mount umount losetup; do
	ln -sfv /system/bin/$bin $PREFIX/bin/$bin
done

cat > $PREFIX/bin/egrep << 'eof'
#!/system/bin/sh
exec grep -E "$@"
eof
cat > $PREFIX/bin/fgrep << 'eof'
#!/system/bin/sh
exec grep -F "$@"
eof
chmod +x $PREFIX/bin/{e,f}grep

for lib in "${COMPRESSION_LIBS[@]}"; do
	pm_install "$lib"

	case "$lib" in
		pigz)
			cd "$PREFIX"/bin
			[ -f gzip ] && mv -v gzip gzip.bak
			[ -f gunzip ] && mv -v gunzip gunzip.bak
			ln -sv pigz gzip
			ln -sv unpigz gunzip
			cd -
			;;
		pixz)
			cd "$PREFIX"/bin
			[ -f xz ] && mv -v xz xz.bak
			[ -f unxz ] && mv -v unxz unxz.bak
			ln -sv pixz xz
			ln -sv unpixz unxz
			cd -
			;;
		plzip)
			cd "$PREFIX"/bin
            [ -f lzip ] && mv -v lzip lzip.bak
			[ -f lunzip ] && mv -v lunzip lunzip.bak
            ln -sv plzip lzip
            ln -sv plzip lunzip
            cd -
            ;;
	esac
done

confirm "Install pacman and co.? (pacman-contrib, pacutils, etc.)" \
	&& PACMAN=1 || PACMAN=0
if (( PACMAN )); then
	pm_install pacman pacman-contrib pacutils fakepkg

	if [ ! -d "$PREFIX/etc/pacman.d/gnupg" ]; then
		_nofail pacman-key --init
		_nofail pacman-key --populate
	fi

	_nofail pacman -Syu
fi


for pkg in "${BASE_PKGS[@]}" "${PKGS[@]}" ; do
	confirm "Install \"${bold}${cyn}${pkg}${rst}\"?" \
		&& pm_install "$pkg"
done

confirm "Install Python 3?" \
	&& PYTHON=1 || PYTHON=0
if (( PYTHON )); then
  pm_install ${PYTHON_PKGS[@]}

  for module in ${PY3_MODULES[@]} ; do
	  confirm "Python 3 module -- \"$module\"?" \
		  && pip install "$module"
  done
fi
unset module

confirm "Ruby?" \
	&& RUBY=1 || RUBY=0
if (( RUBY )); then
	pm_install ruby

	gem update
	gem upgrade
	for gem in ${RB_GEMS} ; do
		gem install $gem
	done
fi
unset gem

NODEJS=1
if (( NODEJS )); then
	pm_install nodejs
	pm_install yarn

	for npmmod in "${NPM_MODULES}" ; do
		npm i -g "${npmmod}"
	done
fi
unset npmmod

LUA=1
LUA_VERS=5.4
if (( LUA )); then
	for pkg in "${LUA_PKGS[@]}" ; do
		pm_install "$pkg"
	done

	luarocks config lua_version "$LUA_VERS"
fi

GRADLE=1
if (( GRADLE )); then
	pm_install ndk-multilib ndk-multilib-native-stubs
	(( STATIC_LIBS )) && pm_install ndk-multilib-native-static
	pm_install x11-repo openjdk-17 openjdk-17-x gradle
fi

TOR=0
if (( TOR )); then
	pm_install tor apt-transport-tor
fi

# vim: ft=bash ts=4 sw=4 ai noet
